
name: CI/CD Order Service - Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Instalar Dependências
        run: pip install -r requirements.txt

      - name: 4. Rodar Testes e Cobertura
        run: pytest --cov=./ --cov-report=xml --cov-fail-under=80

      - name: 5. SonarCloud Scan (Análise de Qualidade)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=IgorCeola_order-service
            -Dsonar.organization=igorceola
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.qualitygate.wait=true

      - name: 6. Acionar Deploy no Render (Staging)
        run: |
          # Usa o comando curl para enviar a requisição POST para o Webhook do Render.
          curl -X POST ${{ secrets.RENDER_DEPLOY_WEBHOOK_STAGING }}
          
      - name: 7. Sucesso na Homologação
        run: echo "Deploy para Homologação concluído com sucesso!"